# my docker compose file
 
version: '3'
services:
 
  db:
    image: mariadb:latest
    volumes:
      - .:/var/lib/mysql:delegated
    tty: true
    container_name: ts-db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: shopware
      MYSQL_USER: root
      MYSQL_PASSWORD: test
    networks:
      - ts-network
    ports:
      - '3307:3306'
networks:
  ts-network:
    driver: bridge

