version: 2.1

jobs:
  run-script:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Spin up services
          command: |
            docker-compose up -d
            # ideally, check MariaDB is ready via dockerize, or a similar tool
            sleep 30
      - run:
          name: Run SQL script against DB
          command: |
            docker exec -i ts-db sh -c 'exec mysql -D"shopware" -u"admin" -p"secret!"' <  test.sql

workflows:
  main:
    jobs:
      - run-script
